# # -*- coding: utf-8 -*-
# """Smart Waste Management-Project

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1_EOunmgvnQ_Zf1YNuJyV5QmqyPONp6E7
# """

# import base64

# try:
#     with open("smart-waste-management.jpg", "rb") as img_file:
#         img_base64 = base64.b64encode(img_file.read()).decode()
# except FileNotFoundError:
#     # This error occurs because the image file 'smart-waste-management.jpg' was not found.
#     # To fix this, you have a few options:
#     # 1. Upload the 'smart-waste-management.jpg' file directly to your Colab environment.
#     #    You can do this by clicking the 'Files' icon on the left sidebar, then 'Upload to session storage'.
#     # 2. If the image is in your Google Drive, first run the cell that mounts Google Drive (Cell Q21Uhaz9b4sh),
#     #    then update the file path. For example, if it's in a folder named 'my_images' in your Drive, the path might be
#     #    '/content/drive/MyDrive/my_images/smart-waste-management.jpg'.
#     # For now, a placeholder base64 string will be used to allow the rest of the notebook to run.
#     print("Error: 'smart-waste-management.jpg' not found. Please upload the file or correct the path.")
#     # Using a transparent 1x1 pixel base64 image as a placeholder to prevent further errors.
#     img_base64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="


# import pandas as pd
# import numpy as np
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import train_test_split
# from IPython.display import HTML, display

# # -------------------------------
# # CREATE DATASET
# # -------------------------------
# data = {
#     "previous_fill": [30, 45, 65, 20, 80, 40, 55, 70, 25, 90],
#     "people_count": [120, 150, 180, 100, 220, 130, 160, 200, 110, 250],
#     "temperature": [32, 34, 35, 30, 36, 31, 33, 37, 29, 38],
#     "fill_level": [45, 65, 85, 35, 95, 55, 75, 90, 40, 98]
# }

# df = pd.DataFrame(data)

# # -------------------------------
# # TRAIN MODEL
# # -------------------------------
# X = df[["previous_fill", "people_count", "temperature"]]
# y = df["fill_level"]

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

# model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)

# # -------------------------------
# # PREDICTION FUNCTION
# # -------------------------------
# def predict_fill(previous_fill, people_count, temperature):
#     input_data = np.array([[previous_fill, people_count, temperature]])
#     prediction = round(model.predict(input_data)[0], 2)
#     return prediction

# # -------------------------------
# # HTML WEB UI
# # -------------------------------
# html_code = f"""
# <style>
#         body {{
#             margin: 0;
#             height: 100vh;
#             display: flex;
#             justify-content: center;
#             align-items: center;

#             /* Background image */
#             background-image: url("data:image/jpg;base64,{img_base64}");
#             background-size: cover;
#             background-position: center;

#             font-family: Arial, sans-serif;
#         }}
#         .wrapper {{
#             width: 100%;
#             height: 100vh;
#             display: flex;
#             justify-content: center;
#             align-items: center;
#         }}

#         .container {{
#             width: 400px;
#             padding: 25px;
#             display:flex ;
#             flex-direction: column;
#             gap:10px;
#             border-radius: 12px;
#             background-color:rgb(141, 189, 141);
#             box-shadow: 0 8px 20px rgba(0,0,0,0.15);
#         }}

#         h2 {{
#             text-align: center;
#             color: #2c6e49;
#         }}

#         label {{
#             font-weight: 600;
#             color: #333;
#         }}

#         input {{
#             width: 100%;
#             padding: 8px;
#             margin-top: 5px;
#             border-radius: 6px;
#             border: 1px solid #ccc;
#         }}

#         button {{
#             width: 100%;
#             padding: 10px;
#             margin-top: 15px;
#             border: none;
#             border-radius: 8px;
#             background-color: #b5e487;
#             color: #003049;
#             font-size: 15px;
#             font-weight: bold;
#             cursor: pointer;
#         }}

#         button:hover {{
#             background-color:rgb(6, 197, 6);
#         }}

#         #output {{
#             margin-top: 20px;
#             font-weight: bold;
#             text-align: center;
#             color: #1b4332;
#         }}
#         button:focus{{
#             border:2px solid black;
#         }}
#     </style>
# </head>

# <body>
# <div class="wrapper">
# <div class="container">
#     <h2>AI Smart Waste Management System</h2>

#     <label>Previous Bin Fill Level (%)</label>
#     <input type="number" id="prev">

#     <label>People Count</label>
#     <input type="number" id="people">

#     <label>Temperature (°C)</label>
#     <input type="number" id="temp">

#     <button onclick="sendData()">Predict Bin Fill Level</button>

#     <p id="output"></p>
# </div>
# </div>

# <script>
# function sendData() {{
#     let prev = document.getElementById("prev").value;
#     let people = document.getElementById("people").value;
#     let temp = document.getElementById("temp").value;

#     google.colab.kernel.invokeFunction(
#         'predict',
#         [prev, people, temp],
#         {{}}
#     );
# }}
# </script>
# """

# display(HTML(html_code))

# # -------------------------------
# # COLAB CALLBACK
# # -------------------------------
# from google.colab import output

# def predict(prev, people, temp):
#     prev = float(prev)
#     people = int(people)
#     temp = float(temp)

#     result = predict_fill(prev, people, temp)

#     if result > 80:
#         message = f"⚠ Predicted Fill Level: {result}% – Immediate waste collection required!"
#     else:
#         message = f"✅ Predicted Fill Level: {result}% – Bin status normal."

#     display(HTML(f"<script>document.getElementById('output').innerHTML='{message}';</script>"))

# output.register_callback('predict', predict)




import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# -------------------------------
# PAGE CONFIGURATION (Styled Background)
# -------------------------------
st.set_page_config(page_title="AI Smart Waste Management", layout="centered")

# Custom CSS styling to match your original green theme palette
st.markdown("""
    <style>
    .stApp {
        background-color: #f4f9f4;
    }
    h1 {
        color: #2c6e49 !important;
        text-align: center;
        font-family: Arial, sans-serif;
    }
    div[data-testid="stMarkdownContainer"] p {
        font-weight: 600;
        color: #333333;
    }
    </style>
""", unsafe_allow_html=True)

st.title("AI Smart Waste Management System")

# -------------------------------
# CREATE DATASET
# -------------------------------
# data = {
#     "previous_fill":,
#     "people_count":,
#     "temperature":,
#     "fill_level": [45, 65, 85, 35, 95, 55, 75, 90, 40, 98]
# }
# df = pd.DataFrame(data)


# -------------------------------
# CREATE DATASET
# -------------------------------
data = {
    "previous_fill": [30, 45, 65, 20, 80, 40, 55, 70, 25, 90],
    "people_count": [120, 150, 180, 100, 220, 130, 160, 200, 110, 250],
    "temperature": [32, 34, 35, 30, 36, 31, 33, 37, 29, 38],
    "fill_level": [45, 65, 85, 35, 95, 55, 75, 90, 40, 98]
}
df = pd.DataFrame(data)

# -------------------------------
# TRAIN MODEL (Cached for speed)
# -------------------------------
@st.cache_resource
def train_waste_model():
    X = df[["previous_fill", "people_count", "temperature"]]
    y = df["fill_level"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    trained_model = RandomForestRegressor(n_estimators=100, random_state=42)
    trained_model.fit(X_train, y_train)
    return trained_model

model = train_waste_model()

# -------------------------------
# PREDICTION FUNCTION
# -------------------------------
def predict_fill(previous_fill, people_count, temperature):
    input_data = np.array([[previous_fill, people_count, temperature]])
    prediction = round(model.predict(input_data)[0], 2)
    return prediction

# -------------------------------
# STREAMLIT USER INTERFACE
# -------------------------------
with st.container():
    # Input Fields
    prev = st.number_input("Previous Bin Fill Level (%)", min_value=0.0, max_value=100.0, value=50.0, step=1.0)
    people = st.number_input("People Count", min_value=0, value=150, step=1)
    temp = st.number_input("Temperature (°C)", min_value=-10.0, max_value=60.0, value=30.0, step=0.5)

    # Predict Button Execution
    if st.button("Predict Bin Fill Level"):
        result = predict_fill(prev, people, temp)
        
        # Displaying tailored outcomes based on fill thresholds
        if result > 80:
            st.error(f"⚠ Predicted Fill Level: {result}% – Immediate waste collection required!")
        else:
            st.success(f"✅ Predicted Fill Level: {result}% – Bin status normal.")
